添加build命令，优化test cover unit命令

diff --git a/build/git-hooks/pre-commit b/build/git-hooks/pre-commit
--- a/build/git-hooks/pre-commit
+++ b/build/git-hooks/pre-commit
@@ -1,9 +1,32 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 # get files to be linted
 FILES=$(git diff --name-only | grep -E '^src|^test/unit/specs')
 
 # lint them if any
-if [[ $FILES ]]; then
-  ./node_modules/.bin/eslint $FILES
+if [[ "$FILES" = "" ]]; then
+  exit 0
 fi
+
+for FILE in $FILES
+do
+  ./node_modules/.bin/eslint "$FILE"
+
+  if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    echo "\t\033[41mESLint Failed: $FILE\033[0m"
+    PASS=false
+  fi
+done
+
+echo "\nJavascript validation completed!\n"
+
+if ! $PASS; then
+  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+  exit 1
+else
+  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
+
+exit $?
